### ISSUE TITLE
Simplifying PON

### ISSUE THREAD

**Issue by Tombez** [wongjiahau/Pineapple#2]
In the [Object specification](https://github.com/wongjiahau/Pineapple/blob/master/specification/Objects.md), do you really need the equal signs or prefixing every property with a `.`?

Example without:
```java
// Pineapple 
myFruit
    name "Mango" 
    isTasty true
    sibling
        name "Durian"
        isTasty false
    amount 10 + 5
```

**Comment by wongjiahau** [comment]
@Tombez 
## Why the `.` is needed?
Because it will allow programmer to **know** how to access the property easier.  
For example:
```ts
myFruit 
    .name = "Pineapple"
    .age    = 12
```
It will be more obvious on how can I access the value `"Pineapple"`, which is using `.` like `myFruit.Pineapple`. 

## Why the `=` sign is needed? 
According to the section [Variable](https://github.com/wongjiahau/Pineapple/blob/master/specification/Variables.md), `=` stands for binding and `<-` stands for assignment, `=` symbol exist because it is to differentiate binding with assignment.  

For example,
```java
myFruit =
    .name = "Pineapple"
    .price <- 20

//trying to modify the name property
myFruit.name = "Banana" // Error: Cannot rebind value
myFruit.price <- 30 // No problem, because you can reassign value 
```
## Conclusion
There is no conclusion yet, to be frank I also don't think the current syntax is quite elegant, so please do let me know if you have better improvement of on the syntax without breaking their previous purpose.  

Anyway, thanks for the suggestion @Tombez. It is really appreciated. :smile:
